// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

type AvailableQuantity struct {
	// id диапазона
	ID int32
	// Количество свободных товаров
	AvailableQuantity int32
}

type GoodsReservation struct {
	// id строки
	ID int32
	// идентификатор заказа
	OrderID string
	// идентификатор товара
	NomenclatureID int32
	// зарезервированное количество товара
	QuantityReserved int32
}
