apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm.fullname" . }}-ingress
  labels:
  {{- include "helm.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: goods.internal
    http:
      paths:
      - backend:
          service:
            name: '{{ include "helm.fullname" . }}-service-lb'
            port:
              number: 80
        path: /
        pathType: Prefix
