// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewReserveParams Резервирование товаров по заказу
//
// swagger:model NewReserveParams
type NewReserveParams struct {

	// goods
	Goods []*NewReserveParamsGoodsItems0 `json:"goods"`

	// Идентификатор заказа
	// Example: Заказ №123
	// Required: true
	OrderID string `json:"order_id"`
}

// Validate validates this new reserve params
func (m *NewReserveParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGoods(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrderID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewReserveParams) validateGoods(formats strfmt.Registry) error {
	if swag.IsZero(m.Goods) { // not required
		return nil
	}

	for i := 0; i < len(m.Goods); i++ {
		if swag.IsZero(m.Goods[i]) { // not required
			continue
		}

		if m.Goods[i] != nil {
			if err := m.Goods[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("goods" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("goods" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *NewReserveParams) validateOrderID(formats strfmt.Registry) error {

	if err := validate.RequiredString("order_id", "body", m.OrderID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this new reserve params based on the context it is used
func (m *NewReserveParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGoods(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewReserveParams) contextValidateGoods(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Goods); i++ {

		if m.Goods[i] != nil {

			if swag.IsZero(m.Goods[i]) { // not required
				return nil
			}

			if err := m.Goods[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("goods" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("goods" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *NewReserveParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewReserveParams) UnmarshalBinary(b []byte) error {
	var res NewReserveParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// NewReserveParamsGoodsItems0 new reserve params goods items0
//
// swagger:model NewReserveParamsGoodsItems0
type NewReserveParamsGoodsItems0 struct {

	// Идентификатор товара
	// Example: 2
	Nomenclature string `json:"nomenclature"`

	// количество товара
	Quantity int64 `json:"quantity"`
}

// Validate validates this new reserve params goods items0
func (m *NewReserveParamsGoodsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this new reserve params goods items0 based on context it is used
func (m *NewReserveParamsGoodsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewReserveParamsGoodsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewReserveParamsGoodsItems0) UnmarshalBinary(b []byte) error {
	var res NewReserveParamsGoodsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
