// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReserveStatus reserve status
//
// swagger:model ReserveStatus
type ReserveStatus struct {

	// Идентификатор заказа
	// Example: Заказ №123
	OrderID string `json:"order_id"`

	// Статус резерва товаров
	// Example: Confirmed
	ReserveStatus string `json:"reserve_status"`
}

// Validate validates this reserve status
func (m *ReserveStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this reserve status based on context it is used
func (m *ReserveStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReserveStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReserveStatus) UnmarshalBinary(b []byte) error {
	var res ReserveStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
