// Code generated by go-swagger; DO NOT EDIT.

package warehouse

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteUnreserveGoodsOrderIDHandlerFunc turns a function with the right signature into a delete unreserve goods order ID handler
type DeleteUnreserveGoodsOrderIDHandlerFunc func(DeleteUnreserveGoodsOrderIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteUnreserveGoodsOrderIDHandlerFunc) Handle(params DeleteUnreserveGoodsOrderIDParams) middleware.Responder {
	return fn(params)
}

// DeleteUnreserveGoodsOrderIDHandler interface for that can handle valid delete unreserve goods order ID params
type DeleteUnreserveGoodsOrderIDHandler interface {
	Handle(DeleteUnreserveGoodsOrderIDParams) middleware.Responder
}

// NewDeleteUnreserveGoodsOrderID creates a new http.Handler for the delete unreserve goods order ID operation
func NewDeleteUnreserveGoodsOrderID(ctx *middleware.Context, handler DeleteUnreserveGoodsOrderIDHandler) *DeleteUnreserveGoodsOrderID {
	return &DeleteUnreserveGoodsOrderID{Context: ctx, Handler: handler}
}

/*
	DeleteUnreserveGoodsOrderID swagger:route DELETE /unreserve-goods/{order-id} Warehouse deleteUnreserveGoodsOrderId

DeleteUnreserveGoodsOrderID delete unreserve goods order ID API
*/
type DeleteUnreserveGoodsOrderID struct {
	Context *middleware.Context
	Handler DeleteUnreserveGoodsOrderIDHandler
}

func (o *DeleteUnreserveGoodsOrderID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteUnreserveGoodsOrderIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
