// Code generated by go-swagger; DO NOT EDIT.

package warehouse

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"otusgoods/internal/models"
)

// DeleteUnreserveGoodsOrderIDOKCode is the HTTP code returned for type DeleteUnreserveGoodsOrderIDOK
const DeleteUnreserveGoodsOrderIDOKCode int = 200

/*
DeleteUnreserveGoodsOrderIDOK Успешное получение данных по балансу

swagger:response deleteUnreserveGoodsOrderIdOK
*/
type DeleteUnreserveGoodsOrderIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewDeleteUnreserveGoodsOrderIDOK creates DeleteUnreserveGoodsOrderIDOK with default headers values
func NewDeleteUnreserveGoodsOrderIDOK() *DeleteUnreserveGoodsOrderIDOK {

	return &DeleteUnreserveGoodsOrderIDOK{}
}

// WithPayload adds the payload to the delete unreserve goods order Id o k response
func (o *DeleteUnreserveGoodsOrderIDOK) WithPayload(payload *models.DefaultStatusResponse) *DeleteUnreserveGoodsOrderIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete unreserve goods order Id o k response
func (o *DeleteUnreserveGoodsOrderIDOK) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUnreserveGoodsOrderIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUnreserveGoodsOrderIDInternalServerErrorCode is the HTTP code returned for type DeleteUnreserveGoodsOrderIDInternalServerError
const DeleteUnreserveGoodsOrderIDInternalServerErrorCode int = 500

/*
DeleteUnreserveGoodsOrderIDInternalServerError Серверная ошибка

swagger:response deleteUnreserveGoodsOrderIdInternalServerError
*/
type DeleteUnreserveGoodsOrderIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewDeleteUnreserveGoodsOrderIDInternalServerError creates DeleteUnreserveGoodsOrderIDInternalServerError with default headers values
func NewDeleteUnreserveGoodsOrderIDInternalServerError() *DeleteUnreserveGoodsOrderIDInternalServerError {

	return &DeleteUnreserveGoodsOrderIDInternalServerError{}
}

// WithPayload adds the payload to the delete unreserve goods order Id internal server error response
func (o *DeleteUnreserveGoodsOrderIDInternalServerError) WithPayload(payload *models.DefaultStatusResponse) *DeleteUnreserveGoodsOrderIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete unreserve goods order Id internal server error response
func (o *DeleteUnreserveGoodsOrderIDInternalServerError) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUnreserveGoodsOrderIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
