// Code generated by go-swagger; DO NOT EDIT.

package warehouse

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"otusgoods/internal/models"
)

// GetCheckReserveStatusOrderIDOKCode is the HTTP code returned for type GetCheckReserveStatusOrderIDOK
const GetCheckReserveStatusOrderIDOKCode int = 200

/*
GetCheckReserveStatusOrderIDOK Успешное получение статуса резерва

swagger:response getCheckReserveStatusOrderIdOK
*/
type GetCheckReserveStatusOrderIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ReserveStatus `json:"body,omitempty"`
}

// NewGetCheckReserveStatusOrderIDOK creates GetCheckReserveStatusOrderIDOK with default headers values
func NewGetCheckReserveStatusOrderIDOK() *GetCheckReserveStatusOrderIDOK {

	return &GetCheckReserveStatusOrderIDOK{}
}

// WithPayload adds the payload to the get check reserve status order Id o k response
func (o *GetCheckReserveStatusOrderIDOK) WithPayload(payload *models.ReserveStatus) *GetCheckReserveStatusOrderIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get check reserve status order Id o k response
func (o *GetCheckReserveStatusOrderIDOK) SetPayload(payload *models.ReserveStatus) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCheckReserveStatusOrderIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCheckReserveStatusOrderIDBadRequestCode is the HTTP code returned for type GetCheckReserveStatusOrderIDBadRequest
const GetCheckReserveStatusOrderIDBadRequestCode int = 400

/*
GetCheckReserveStatusOrderIDBadRequest Клиентская ошибка

swagger:response getCheckReserveStatusOrderIdBadRequest
*/
type GetCheckReserveStatusOrderIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCheckReserveStatusOrderIDBadRequest creates GetCheckReserveStatusOrderIDBadRequest with default headers values
func NewGetCheckReserveStatusOrderIDBadRequest() *GetCheckReserveStatusOrderIDBadRequest {

	return &GetCheckReserveStatusOrderIDBadRequest{}
}

// WithPayload adds the payload to the get check reserve status order Id bad request response
func (o *GetCheckReserveStatusOrderIDBadRequest) WithPayload(payload *models.Error) *GetCheckReserveStatusOrderIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get check reserve status order Id bad request response
func (o *GetCheckReserveStatusOrderIDBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCheckReserveStatusOrderIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCheckReserveStatusOrderIDInternalServerErrorCode is the HTTP code returned for type GetCheckReserveStatusOrderIDInternalServerError
const GetCheckReserveStatusOrderIDInternalServerErrorCode int = 500

/*
GetCheckReserveStatusOrderIDInternalServerError Серверная ошибка

swagger:response getCheckReserveStatusOrderIdInternalServerError
*/
type GetCheckReserveStatusOrderIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCheckReserveStatusOrderIDInternalServerError creates GetCheckReserveStatusOrderIDInternalServerError with default headers values
func NewGetCheckReserveStatusOrderIDInternalServerError() *GetCheckReserveStatusOrderIDInternalServerError {

	return &GetCheckReserveStatusOrderIDInternalServerError{}
}

// WithPayload adds the payload to the get check reserve status order Id internal server error response
func (o *GetCheckReserveStatusOrderIDInternalServerError) WithPayload(payload *models.Error) *GetCheckReserveStatusOrderIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get check reserve status order Id internal server error response
func (o *GetCheckReserveStatusOrderIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCheckReserveStatusOrderIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
