// Code generated by go-swagger; DO NOT EDIT.

package warehouse

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"otusgoods/internal/models"
)

// PostReserveOrderGoodsOKCode is the HTTP code returned for type PostReserveOrderGoodsOK
const PostReserveOrderGoodsOKCode int = 200

/*
PostReserveOrderGoodsOK Успешное создание пользователя

swagger:response postReserveOrderGoodsOK
*/
type PostReserveOrderGoodsOK struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewPostReserveOrderGoodsOK creates PostReserveOrderGoodsOK with default headers values
func NewPostReserveOrderGoodsOK() *PostReserveOrderGoodsOK {

	return &PostReserveOrderGoodsOK{}
}

// WithPayload adds the payload to the post reserve order goods o k response
func (o *PostReserveOrderGoodsOK) WithPayload(payload *models.DefaultStatusResponse) *PostReserveOrderGoodsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post reserve order goods o k response
func (o *PostReserveOrderGoodsOK) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostReserveOrderGoodsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostReserveOrderGoodsBadRequestCode is the HTTP code returned for type PostReserveOrderGoodsBadRequest
const PostReserveOrderGoodsBadRequestCode int = 400

/*
PostReserveOrderGoodsBadRequest Клиентская ошибка

swagger:response postReserveOrderGoodsBadRequest
*/
type PostReserveOrderGoodsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewPostReserveOrderGoodsBadRequest creates PostReserveOrderGoodsBadRequest with default headers values
func NewPostReserveOrderGoodsBadRequest() *PostReserveOrderGoodsBadRequest {

	return &PostReserveOrderGoodsBadRequest{}
}

// WithPayload adds the payload to the post reserve order goods bad request response
func (o *PostReserveOrderGoodsBadRequest) WithPayload(payload *models.DefaultStatusResponse) *PostReserveOrderGoodsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post reserve order goods bad request response
func (o *PostReserveOrderGoodsBadRequest) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostReserveOrderGoodsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostReserveOrderGoodsInternalServerErrorCode is the HTTP code returned for type PostReserveOrderGoodsInternalServerError
const PostReserveOrderGoodsInternalServerErrorCode int = 500

/*
PostReserveOrderGoodsInternalServerError Серверная ошибка

swagger:response postReserveOrderGoodsInternalServerError
*/
type PostReserveOrderGoodsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewPostReserveOrderGoodsInternalServerError creates PostReserveOrderGoodsInternalServerError with default headers values
func NewPostReserveOrderGoodsInternalServerError() *PostReserveOrderGoodsInternalServerError {

	return &PostReserveOrderGoodsInternalServerError{}
}

// WithPayload adds the payload to the post reserve order goods internal server error response
func (o *PostReserveOrderGoodsInternalServerError) WithPayload(payload *models.DefaultStatusResponse) *PostReserveOrderGoodsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post reserve order goods internal server error response
func (o *PostReserveOrderGoodsInternalServerError) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostReserveOrderGoodsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
