// Code generated by go-swagger; DO NOT EDIT.

package warehouse

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"otusgoods/internal/models"
)

// NewPostReserveOrderGoodsParams creates a new PostReserveOrderGoodsParams object
//
// There are no default values defined in the spec.
func NewPostReserveOrderGoodsParams() PostReserveOrderGoodsParams {

	return PostReserveOrderGoodsParams{}
}

// PostReserveOrderGoodsParams contains all the bound params for the post reserve order goods operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostReserveOrderGoods
type PostReserveOrderGoodsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Параметры пополнения баланса
	  Required: true
	  In: body
	*/
	Request *models.NewReserveParams
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostReserveOrderGoodsParams() beforehand.
func (o *PostReserveOrderGoodsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.NewReserveParams
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("request", "body", ""))
			} else {
				res = append(res, errors.NewParseError("request", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Request = &body
			}
		}
	} else {
		res = append(res, errors.Required("request", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
