// Code generated by go-swagger; DO NOT EDIT.

package warehouse

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostReserveOrderGoodsHandlerFunc turns a function with the right signature into a post reserve order goods handler
type PostReserveOrderGoodsHandlerFunc func(PostReserveOrderGoodsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostReserveOrderGoodsHandlerFunc) Handle(params PostReserveOrderGoodsParams) middleware.Responder {
	return fn(params)
}

// PostReserveOrderGoodsHandler interface for that can handle valid post reserve order goods params
type PostReserveOrderGoodsHandler interface {
	Handle(PostReserveOrderGoodsParams) middleware.Responder
}

// NewPostReserveOrderGoods creates a new http.Handler for the post reserve order goods operation
func NewPostReserveOrderGoods(ctx *middleware.Context, handler PostReserveOrderGoodsHandler) *PostReserveOrderGoods {
	return &PostReserveOrderGoods{Context: ctx, Handler: handler}
}

/*
	PostReserveOrderGoods swagger:route POST /reserve-order-goods Warehouse postReserveOrderGoods

Резервирование товаров
*/
type PostReserveOrderGoods struct {
	Context *middleware.Context
	Handler PostReserveOrderGoodsHandler
}

func (o *PostReserveOrderGoods) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostReserveOrderGoodsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
